udo: required

services: 
  docker

env:
  global:
    - SHA=$(git rev-parse HEAD)
    # the belowone is to bypass the user prompts of gcloud things
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1
    #- DNS="dissol.co.uk"
    - DNS=""

before_install:
  - openssl aes-256-cbc -K $encrypted_0c35eebf403c_key -iv $encrypted_0c35eebf403c_iv -in jenkins-k8s-service-account.json.enc -out jenkins-k8s-service-account.json -d
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl
  - gcloud auth activate-service-account --key-file jenkins-k8s-service-account.json
  - gcloud config set project jenkins-k8s-235016
  - gcloud config set compute/zone us-central1-a
  - gcloud container clusters get-credentials jenkins-cluster
  # Login into Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t dandu1008/jenkins-master:test -f ./master/Dockerfile ./master

script:
  - docker run dandu1008/jenkins-master:test echo "Hello Docker"

deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    branch: master
